spring:
  datasource:
    url: jdbc:postgresql://db.lsxkytxcjumnyabpewii.supabase.co:5432/postgres
    username: postgres
    password: VaK3k8/YPPcQ^#+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8080}
  error:
    include-message: always

cors:
  allowed-origins: "*"